// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkizdgeyzfddehlglhfz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZraXpkZ2V5emZkZGVobGdsaGZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5ODI2MTgsImV4cCI6MjA1NzU1ODYxOH0.D_9Sy1ctH4uRvv1cmi4iGmqjzGrsGheRn7jVnueobeI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);